### ISSUE TITLE
за что мне это все

### ISSUE THREAD

**Issue by strokegmd** [andrewzaycew/Hack-test-Backend#1]
жду версию на телетхоне

**Comment by strokegmd** [comment]
и с потоками пж

**Comment by andrewzaycew** [comment]
Или нахуй со своими потоками
Это шаблон, сам добавляй

**Comment by strokegmd** [comment]
бля ты ахуел

**Comment by strokegmd** [comment]
ятвою маму ебал блять

**Comment by strokegmd** [comment]
где потоки мои за что я продаю скрипт по 5 долларов
